INPUT:
  IMAGE_MEAN: [0.406, 0.456, 0.485]
  IMAGE_STD: [0.225, 0.224, 0.229]
  MIN_DIM: 448 # 360 # 449
  MAX_DIM: 768 # 704 # 801
  MAX_IMAGE_AREA: 300000
  NUM_QUERY_FRAMES: -1
  RGB_INPUT: True
  NORMALIZE_TO_UNIT_SCALE: True
MODEL:
  TRANSFORMER_PRE_NORMALIZE: False
  ENCODER_LAYERS: 5
  DECODER_LAYERS: 5
  NUM_ATTN_HEADS: 8
  NUM_BG_DESCRIPTORS: 9
  NUM_CATCH_ALL_QUERIES: 1
  POS_ENCODINGS_IN_FMQ: True
  POS_ENCODINGS_IN_FQM: True
TRAINING:
  NUM_INSTANCES: 4
  MODE: ""
  LR_SCHEDULER: "step"
  BASE_LR: 0.0001
  TOTAL_ITERATIONS: 300000
  BATCH_SIZE: 8
  ACCUMULATE_GRADIENTS: True
  NUM_OTHER_FRAMES: 0
  DETACH_INTERMEDIATE_MASKS: True
  MIN_CLIP_DELTA: 1
  MAX_CLIP_DELTA: 10
  MIN_REF_MASK_AREA: 5000
  MIN_REF_MASK_DIM: 100
  INTERMEDIATE_FRAME_GT_AVAILABLE: True
  APPLY_LOSS_ON_INTERMEDIATE_FRAMES: True
  AUGMENTATIONS:
    COLOR: False
    CROPPING: False
    VIDEO_GEOMETRIC: False
  LR_SCHEDULERS:
    WARMUP:
      WARMUP_ITERS: 10000
      WARMUP_LR_INIT: 1.e-7
    STEP:
      WARMUP_ITERS: 10000
      WARMUP_LR_INIT: 0.0000005  # 5e-7
      BASE_LR: 0.0001
      STEPS: [100000, 160000]
      DECAY_RATES: [0.1, 0.1]
DATA:
  DENSE_VIDEO_SPLIT:
    YTVOS: 0.8
    DAVIS: 0.2
  SPARSE_VIDEO_SPLIT:
    YOUTUBE_VOS: 0.4
    DAVIS: 0.1
