INPUT:
  IMAGE_MEAN: [103.53, 116.28, 123.675]
  IMAGE_STD: [57.375, 57.12, 58.395]
  MIN_DIM: 576 # 320 # 604 # 448
  MAX_DIM: 1200 # 604 # 1024 # 864
  RGB_INPUT: True
  NORMALIZE_TO_UNIT_SCALE: False
MODEL:
  TRANSFORMER_PRE_NORMALIZE: False
  ENCODER_LAYERS: 5
  DECODER_LAYERS: 5
  NUM_ATTN_HEADS: 8
  NUM_BG_DESCRIPTORS: 9
  POS_ENCODINGS_IN_FMQ: False
  POS_ENCODINGS_IN_FQM: True
TRAINING:
  MODE: "dense_video"
  NUM_OTHER_FRAMES: 2
  NUM_INSTANCES: 4
  LR_SCHEDULER: "warmup"
  BASE_LR: 1.0e-5
  TOTAL_ITERATIONS: 100000
  BATCH_SIZE: 8
  ACCUMULATE_GRADIENTS: True
  DETACH_INTERMEDIATE_MASKS: True
  INTERMEDIATE_FRAME_GT_AVAILABLE: True
  MIN_REF_MASK_AREA: 2000
  MIN_REF_MASK_DIM: 20
  MIN_CLIP_DELTA: 1
  MAX_CLIP_DELTA: 8
  AUGMENTATIONS:
    COLOR: True
    CROPPING: True
  LR_SCHEDULERS:
    WARMUP:
      WARMUP_ITERS: 10000
      WARMUP_LR_INIT: 1.e-8
    STEP:
      WARMUP_ITERS: 10000
      WARMUP_LR_INIT: 1.e-7
      STEPS: [100000]
      DECAY_RATES: [0.1]
DATA:
  DENSE_VIDEO_SPLIT:
    YTVOS: 0.8
    DAVIS: 0.2