INPUT:
  IMAGE_MEAN: [103.53, 116.28, 123.675]
  IMAGE_STD: [57.375, 57.12, 58.395]
  MAX_DIM: 864
  MAX_IMAGE_AREA: 300000
  MIN_DIM: 448
  NORMALIZE_TO_UNIT_SCALE: false
  NUM_QUERY_FRAMES: -1
  RGB_INPUT: true
MODEL:
  ENCODER_LAYERS: 5
  DECODER_LAYERS: 5
  NUM_ATTN_HEADS: 8
  NUM_BG_DESCRIPTORS: 9
  NUM_CATCH_ALL_QUERIES: 1
  POS_ENCODINGS_IN_FMQ: false
  POS_ENCODINGS_IN_FQM: true
  TRANSFORMER_PRE_NORMALIZE: false
TRAINING:
  ACCUMULATE_GRADIENTS: true
  AUGMENTATIONS:
    COLOR: true
    CROPPING: true
    VIDEO_GEOMETRIC: false
  BASE_LR: 0.0001
  BATCH_SIZE: 8
  DETACH_INTERMEDIATE_MASKS: true
  INTERMEDIATE_FRAME_GT_AVAILABLE: true
  LR_SCHEDULER: step
  LR_SCHEDULERS:
    STEP:
      BASE_LR: 0.0001
      DECAY_RATES: [0.1]
      STEPS: [100000]
      WARMUP_ITERS: 10000
      WARMUP_LR_INIT: 1.0e-07
    WARMUP:
      WARMUP_ITERS: 10000
      WARMUP_LR_INIT: 1.0e-07
  MAX_CLIP_DELTA: 10
  MIN_CLIP_DELTA: 1
  MIN_REF_MASK_AREA: 2000
  MIN_REF_MASK_DIM: 20
  MODE: "static_image"
  NUM_INSTANCES: 4
  NUM_OTHER_FRAMES: 2
  TOTAL_ITERATIONS: 250000
